import { Send, Type, Database, Film, Clock, GitCompare, Code2, CaseSensitive, ArrowLeftRight, Hash as HashIcon, Shield, Fingerprint, FileText, Music, Maximize2, Key, Link, Terminal, Table, Calculator, ShieldCheck, Search, BookOpen, AlignLeft, Calendar, Globe, Lock, Unlock, Image } from 'lucide-react';
import { Tool } from '@/utils';

export const TOOLS: Tool[] = [
    {
        id: 'api-tester',
        name: 'API Tester',
        description: 'Test HTTP endpoints instantly',
        icon: Send,
        category: 'api',
        path: '/tools/api-tester',
    },
    {
        id: 'jwt-inspector',
        name: 'JWT Inspector',
        description: 'Decode and inspect JWT tokens — header, payload, expiry',
        icon: Key,
        category: 'api',
        path: '/tools/jwt-inspector',
    },
    {
        id: 'url-parser',
        name: 'URL Parser & Builder',
        description: 'Break down and reconstruct URLs with query parameters',
        icon: Link,
        category: 'api',
        path: '/tools/url-parser',
    },
    {
        id: 'curl-converter',
        name: 'cURL ↔ Fetch Converter',
        description: 'Convert cURL commands to fetch/Axios and back',
        icon: Terminal,
        category: 'api',
        path: '/tools/curl-converter',
    },
    {
        id: 'cors-checker',
        name: 'CORS Preflight Checker',
        description: 'Test CORS configuration and check if requests are allowed',
        icon: Shield,
        category: 'api',
        path: '/tools/cors-checker',
    },
    {
        id: 'base64-encoder',
        name: 'Base64 Encoder/Decoder',
        description: 'Encode or decode text to/from Base64',
        icon: Database,
        category: 'data',
        path: '/tools/base64-encoder',
    },
    {
        id: 'json-formatter',
        name: 'JSON Formatter & Validator',
        description: 'Pretty-print, minify, and validate JSON with error highlighting',
        icon: Code2,
        category: 'data',
        path: '/tools/json-formatter',
    },
    {
        id: 'json-yaml-converter',
        name: 'JSON ↔ YAML Converter',
        description: 'Convert between JSON and YAML formats',
        icon: ArrowLeftRight,
        category: 'data',
        path: '/tools/json-yaml-converter',
    },
    {
        id: 'csv-json-converter',
        name: 'CSV ↔ JSON Converter',
        description: 'Convert CSV to JSON array and back with custom delimiters',
        icon: Table,
        category: 'data',
        path: '/tools/csv-json-converter',
    },
    {
        id: 'number-base-converter',
        name: 'Number Base Converter',
        description: 'Convert integers between decimal, binary, octal, and hex',
        icon: Calculator,
        category: 'data',
        path: '/tools/number-base-converter',
    },
    {
        id: 'hash-generator',
        name: 'Hash Generator',
        description: 'Generate cryptographic hashes',
        icon: HashIcon,
        category: 'data',
        path: '/tools/hash-generator',
    },
    {
        id: 'format-aware-diff',
        name: 'Format-Aware Diff',
        description: 'Compare code with normalized whitespace',
        icon: GitCompare,
        category: 'text',
        path: '/tools/format-aware-diff',
    },
    {
        id: 'text-escape',
        name: 'Text Escape/Unescape',
        description: 'Encode or decode text in various formats',
        icon: Type,
        category: 'text',
        path: '/tools/text-escape',
    },
    {
        id: 'code-formatter',
        name: 'Code Minifier/Beautifier',
        description: 'Format or minify code in various languages',
        icon: Code2,
        category: 'text',
        path: '/tools/code-formatter',
    },
    {
        id: 'case-converter',
        name: 'String Case Converter',
        description: 'Convert text between different case formats',
        icon: CaseSensitive,
        category: 'text',
        path: '/tools/case-converter',
    },
    {
        id: 'regex-tester',
        name: 'Regex Tester',
        description: 'Test regular expressions with live match highlighting',
        icon: Search,
        category: 'text',
        path: '/tools/regex-tester',
    },
    {
        id: 'markdown-preview',
        name: 'Markdown Previewer',
        description: 'Write Markdown and see the rendered output side by side',
        icon: BookOpen,
        category: 'text',
        path: '/tools/markdown-preview',
    },
    {
        id: 'lorem-ipsum',
        name: 'Lorem Ipsum Generator',
        description: 'Generate placeholder text by words, sentences, or paragraphs',
        icon: AlignLeft,
        category: 'text',
        path: '/tools/lorem-ipsum',
    },
    {
        id: 'epoch-converter',
        name: 'Epoch Time Converter',
        description: 'Convert between human-readable dates and Unix timestamps',
        icon: Clock,
        category: 'time',
        path: '/tools/epoch-converter',
    },
    {
        id: 'uuid-generator',
        name: 'UUID Generator',
        description: 'Generate UUIDs (v4 random or v7 timestamp-based)',
        icon: Fingerprint,
        category: 'time',
        path: '/tools/uuid-generator',
    },
    {
        id: 'cron-parser',
        name: 'Cron Expression Parser',
        description: 'Translate cron expressions to plain English with next run times',
        icon: Calendar,
        category: 'time',
        path: '/tools/cron-parser',
    },
    {
        id: 'timezone-converter',
        name: 'Timezone Converter',
        description: 'Convert datetimes between any two IANA timezones',
        icon: Globe,
        category: 'time',
        path: '/tools/timezone-converter',
    },
    {
        id: 'password-generator',
        name: 'Password Generator',
        description: 'Generate strong passwords with configurable rules and entropy score',
        icon: Lock,
        category: 'security',
        path: '/tools/password-generator',
    },
    {
        id: 'hmac-generator',
        name: 'HMAC Generator',
        description: 'Generate HMAC-SHA256/512 signatures for webhook verification',
        icon: ShieldCheck,
        category: 'security',
        path: '/tools/hmac-generator',
    },
    {
        id: 'jwt-generator',
        name: 'JWT Generator & Signer',
        description: 'Build and sign JWT tokens with HS256/HS512 for auth testing',
        icon: Unlock,
        category: 'security',
        path: '/tools/jwt-generator',
    },
    {
        id: 'ffmpeg-clipper',
        name: 'FFmpeg Clipper & Converter',
        description: 'Generate FFmpeg commands for clipping and converting videos',
        icon: Film,
        category: 'ffmpeg',
        path: '/tools/ffmpeg-clipper',
    },
    {
        id: 'ffmpeg-subtitle-watermark',
        name: 'FFmpeg Subtitle/Watermark Burner',
        description: 'Generate FFmpeg commands to burn subtitles or watermarks',
        icon: FileText,
        category: 'ffmpeg',
        path: '/tools/ffmpeg-subtitle-watermark',
    },
    {
        id: 'ffmpeg-audio-extractor',
        name: 'FFmpeg Audio Extractor',
        description: 'Generate FFmpeg commands to extract audio from videos',
        icon: Music,
        category: 'ffmpeg',
        path: '/tools/ffmpeg-audio-extractor',
    },
    {
        id: 'ffmpeg-video-resize',
        name: 'FFmpeg Video Resize & Scale',
        description: 'Generate FFmpeg commands to resize and scale videos',
        icon: Maximize2,
        category: 'ffmpeg',
        path: '/tools/ffmpeg-video-resize',
    },
    {
        id: 'ffmpeg-thumbnail',
        name: 'FFmpeg Thumbnail Extractor',
        description: 'Generate FFmpeg commands to extract frames as images',
        icon: Image,
        category: 'ffmpeg',
        path: '/tools/ffmpeg-thumbnail',
    },
];

export function getToolById(id: string): Tool | undefined {
    return TOOLS.find(tool => tool.id === id);
}

export function getToolsByCategory(category: string): Tool[] {
    return TOOLS.filter(tool => tool.category === category);
}
